// Code generated by MockGen. DO NOT EDIT.
// Source: user_registration.go
//
// Generated by this command:
//
//	mockgen -source=user_registration.go -destination=../../storage/mock/mock_user_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/Luclpor/loyalty_system.git/internal/storage/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CheckExistLogin mocks base method.
func (m *MockUserRepository) CheckExistLogin(ctx context.Context, login string) (*bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExistLogin", ctx, login)
	ret0, _ := ret[0].(*bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExistLogin indicates an expected call of CheckExistLogin.
func (mr *MockUserRepositoryMockRecorder) CheckExistLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExistLogin", reflect.TypeOf((*MockUserRepository)(nil).CheckExistLogin), ctx, login)
}

// CreateUserAndBalance mocks base method.
func (m *MockUserRepository) CreateUserAndBalance(ctx context.Context, login, hashPassword string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserAndBalance", ctx, login, hashPassword)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserAndBalance indicates an expected call of CreateUserAndBalance.
func (mr *MockUserRepositoryMockRecorder) CreateUserAndBalance(ctx, login, hashPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserAndBalance", reflect.TypeOf((*MockUserRepository)(nil).CreateUserAndBalance), ctx, login, hashPassword)
}

// GetUserByLogin mocks base method.
func (m *MockUserRepository) GetUserByLogin(ctx context.Context, login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockUserRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockUserRepository)(nil).GetUserByLogin), ctx, login)
}
