// Code generated by MockGen. DO NOT EDIT.
// Source: balance_manager.go
//
// Generated by this command:
//
//	mockgen -source=balance_manager.go -destination=../../storage/mock/mock_balance_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	accrualStatusOrder "github.com/Luclpor/loyalty_system.git/internal/service/order/dto/accrualStatusOrder"
	balanceDto "github.com/Luclpor/loyalty_system.git/internal/service/userBalance/balanceDto"
	models "github.com/Luclpor/loyalty_system.git/internal/storage/models"
	uuid "github.com/google/uuid"
	v5 "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceUpdater is a mock of BalanceUpdater interface.
type MockBalanceUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUpdaterMockRecorder
	isgomock struct{}
}

// MockBalanceUpdaterMockRecorder is the mock recorder for MockBalanceUpdater.
type MockBalanceUpdaterMockRecorder struct {
	mock *MockBalanceUpdater
}

// NewMockBalanceUpdater creates a new mock instance.
func NewMockBalanceUpdater(ctrl *gomock.Controller) *MockBalanceUpdater {
	mock := &MockBalanceUpdater{ctrl: ctrl}
	mock.recorder = &MockBalanceUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUpdater) EXPECT() *MockBalanceUpdaterMockRecorder {
	return m.recorder
}

// SafetyUpdateBalance mocks base method.
func (m *MockBalanceUpdater) SafetyUpdateBalance(ctx context.Context, entToUpdate *accrualStatusOrder.OrderDto) (*models.HistoryBalanceOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SafetyUpdateBalance", ctx, entToUpdate)
	ret0, _ := ret[0].(*models.HistoryBalanceOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SafetyUpdateBalance indicates an expected call of SafetyUpdateBalance.
func (mr *MockBalanceUpdaterMockRecorder) SafetyUpdateBalance(ctx, entToUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SafetyUpdateBalance", reflect.TypeOf((*MockBalanceUpdater)(nil).SafetyUpdateBalance), ctx, entToUpdate)
}

// SafetyWithdrawUpdateBalance mocks base method.
func (m *MockBalanceUpdater) SafetyWithdrawUpdateBalance(ctx context.Context, wdDto *balanceDto.WithdrawUpdateBalanceDto) (*models.HistoryBalanceOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SafetyWithdrawUpdateBalance", ctx, wdDto)
	ret0, _ := ret[0].(*models.HistoryBalanceOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SafetyWithdrawUpdateBalance indicates an expected call of SafetyWithdrawUpdateBalance.
func (mr *MockBalanceUpdaterMockRecorder) SafetyWithdrawUpdateBalance(ctx, wdDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SafetyWithdrawUpdateBalance", reflect.TypeOf((*MockBalanceUpdater)(nil).SafetyWithdrawUpdateBalance), ctx, wdDto)
}

// MockBalanceReader is a mock of BalanceReader interface.
type MockBalanceReader struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceReaderMockRecorder
	isgomock struct{}
}

// MockBalanceReaderMockRecorder is the mock recorder for MockBalanceReader.
type MockBalanceReaderMockRecorder struct {
	mock *MockBalanceReader
}

// NewMockBalanceReader creates a new mock instance.
func NewMockBalanceReader(ctrl *gomock.Controller) *MockBalanceReader {
	mock := &MockBalanceReader{ctrl: ctrl}
	mock.recorder = &MockBalanceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceReader) EXPECT() *MockBalanceReaderMockRecorder {
	return m.recorder
}

// GetUserBalance mocks base method.
func (m *MockBalanceReader) GetUserBalance(ctx context.Context, userID uuid.UUID) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalance", ctx, userID)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalance indicates an expected call of GetUserBalance.
func (mr *MockBalanceReaderMockRecorder) GetUserBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalance", reflect.TypeOf((*MockBalanceReader)(nil).GetUserBalance), ctx, userID)
}

// GetUserBalanceHistoryNegativeTransaction mocks base method.
func (m *MockBalanceReader) GetUserBalanceHistoryNegativeTransaction(ctx context.Context, userID uuid.UUID) ([]models.HistoryBalanceOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalanceHistoryNegativeTransaction", ctx, userID)
	ret0, _ := ret[0].([]models.HistoryBalanceOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalanceHistoryNegativeTransaction indicates an expected call of GetUserBalanceHistoryNegativeTransaction.
func (mr *MockBalanceReaderMockRecorder) GetUserBalanceHistoryNegativeTransaction(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalanceHistoryNegativeTransaction", reflect.TypeOf((*MockBalanceReader)(nil).GetUserBalanceHistoryNegativeTransaction), ctx, userID)
}

// GetUsersBalances mocks base method.
func (m *MockBalanceReader) GetUsersBalances(ctx context.Context, userIDs []uuid.UUID) ([]models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersBalances", ctx, userIDs)
	ret0, _ := ret[0].([]models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersBalances indicates an expected call of GetUsersBalances.
func (mr *MockBalanceReaderMockRecorder) GetUsersBalances(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersBalances", reflect.TypeOf((*MockBalanceReader)(nil).GetUsersBalances), ctx, userIDs)
}

// GetWithDraws mocks base method.
func (m *MockBalanceReader) GetWithDraws(ctx context.Context, userID uuid.UUID) ([]models.HistoryBalanceOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithDraws", ctx, userID)
	ret0, _ := ret[0].([]models.HistoryBalanceOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithDraws indicates an expected call of GetWithDraws.
func (mr *MockBalanceReaderMockRecorder) GetWithDraws(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithDraws", reflect.TypeOf((*MockBalanceReader)(nil).GetWithDraws), ctx, userID)
}

// MockHistoryBalancer is a mock of HistoryBalancer interface.
type MockHistoryBalancer struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryBalancerMockRecorder
	isgomock struct{}
}

// MockHistoryBalancerMockRecorder is the mock recorder for MockHistoryBalancer.
type MockHistoryBalancerMockRecorder struct {
	mock *MockHistoryBalancer
}

// NewMockHistoryBalancer creates a new mock instance.
func NewMockHistoryBalancer(ctrl *gomock.Controller) *MockHistoryBalancer {
	mock := &MockHistoryBalancer{ctrl: ctrl}
	mock.recorder = &MockHistoryBalancerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryBalancer) EXPECT() *MockHistoryBalancerMockRecorder {
	return m.recorder
}

// CreateNewBalanceHistoryTransaction mocks base method.
func (m *MockHistoryBalancer) CreateNewBalanceHistoryTransaction(ctx context.Context, tx v5.Tx, hisBalanceEntity *models.HistoryBalanceOperation) (*models.HistoryBalanceOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewBalanceHistoryTransaction", ctx, tx, hisBalanceEntity)
	ret0, _ := ret[0].(*models.HistoryBalanceOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewBalanceHistoryTransaction indicates an expected call of CreateNewBalanceHistoryTransaction.
func (mr *MockHistoryBalancerMockRecorder) CreateNewBalanceHistoryTransaction(ctx, tx, hisBalanceEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewBalanceHistoryTransaction", reflect.TypeOf((*MockHistoryBalancer)(nil).CreateNewBalanceHistoryTransaction), ctx, tx, hisBalanceEntity)
}
