// Code generated by MockGen. DO NOT EDIT.
// Source: order.go
//
// Generated by this command:
//
//	mockgen -source=order.go -destination=../../storage/mock/mock_order_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/Luclpor/loyalty_system.git/internal/storage/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderSaver is a mock of OrderSaver interface.
type MockOrderSaver struct {
	ctrl     *gomock.Controller
	recorder *MockOrderSaverMockRecorder
	isgomock struct{}
}

// MockOrderSaverMockRecorder is the mock recorder for MockOrderSaver.
type MockOrderSaverMockRecorder struct {
	mock *MockOrderSaver
}

// NewMockOrderSaver creates a new mock instance.
func NewMockOrderSaver(ctrl *gomock.Controller) *MockOrderSaver {
	mock := &MockOrderSaver{ctrl: ctrl}
	mock.recorder = &MockOrderSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderSaver) EXPECT() *MockOrderSaverMockRecorder {
	return m.recorder
}

// SaveOrder mocks base method.
func (m *MockOrderSaver) SaveOrder(ctx context.Context, orderDto *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", ctx, orderDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockOrderSaverMockRecorder) SaveOrder(ctx, orderDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockOrderSaver)(nil).SaveOrder), ctx, orderDto)
}

// UpdateOrdersStatus mocks base method.
func (m *MockOrderSaver) UpdateOrdersStatus(ctx context.Context, entToUpd *models.Order) (models.OrderStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrdersStatus", ctx, entToUpd)
	ret0, _ := ret[0].(models.OrderStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrdersStatus indicates an expected call of UpdateOrdersStatus.
func (mr *MockOrderSaverMockRecorder) UpdateOrdersStatus(ctx, entToUpd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrdersStatus", reflect.TypeOf((*MockOrderSaver)(nil).UpdateOrdersStatus), ctx, entToUpd)
}

// MockOrderReader is a mock of OrderReader interface.
type MockOrderReader struct {
	ctrl     *gomock.Controller
	recorder *MockOrderReaderMockRecorder
	isgomock struct{}
}

// MockOrderReaderMockRecorder is the mock recorder for MockOrderReader.
type MockOrderReaderMockRecorder struct {
	mock *MockOrderReader
}

// NewMockOrderReader creates a new mock instance.
func NewMockOrderReader(ctrl *gomock.Controller) *MockOrderReader {
	mock := &MockOrderReader{ctrl: ctrl}
	mock.recorder = &MockOrderReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderReader) EXPECT() *MockOrderReaderMockRecorder {
	return m.recorder
}

// GetOrderByID mocks base method.
func (m *MockOrderReader) GetOrderByID(ctx context.Context, orderID string) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, orderID)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderReaderMockRecorder) GetOrderByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderReader)(nil).GetOrderByID), ctx, orderID)
}

// GetOrdersByUserID mocks base method.
func (m *MockOrderReader) GetOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockOrderReaderMockRecorder) GetOrdersByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockOrderReader)(nil).GetOrdersByUserID), ctx, userID)
}
