// Code generated by MockGen. DO NOT EDIT.
// Source: order_worker.go
//
// Generated by this command:
//
//	mockgen -source=order_worker.go -destination=../mock/mock_order_dependencies.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/Luclpor/loyalty_system.git/internal/service/order/dto"
	accrualStatusOrder "github.com/Luclpor/loyalty_system.git/internal/service/order/dto/accrualStatusOrder"
	models "github.com/Luclpor/loyalty_system.git/internal/storage/models"
	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockbalanceManagerService is a mock of balanceManagerService interface.
type MockbalanceManagerService struct {
	ctrl     *gomock.Controller
	recorder *MockbalanceManagerServiceMockRecorder
	isgomock struct{}
}

// MockbalanceManagerServiceMockRecorder is the mock recorder for MockbalanceManagerService.
type MockbalanceManagerServiceMockRecorder struct {
	mock *MockbalanceManagerService
}

// NewMockbalanceManagerService creates a new mock instance.
func NewMockbalanceManagerService(ctrl *gomock.Controller) *MockbalanceManagerService {
	mock := &MockbalanceManagerService{ctrl: ctrl}
	mock.recorder = &MockbalanceManagerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbalanceManagerService) EXPECT() *MockbalanceManagerServiceMockRecorder {
	return m.recorder
}

// UpdateBalance mocks base method.
func (m *MockbalanceManagerService) UpdateBalance(ctx context.Context, order *accrualStatusOrder.OrderDto) (*models.HistoryBalanceOperation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, order)
	ret0, _ := ret[0].(*models.HistoryBalanceOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockbalanceManagerServiceMockRecorder) UpdateBalance(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockbalanceManagerService)(nil).UpdateBalance), ctx, order)
}

// MockorderManagerService is a mock of orderManagerService interface.
type MockorderManagerService struct {
	ctrl     *gomock.Controller
	recorder *MockorderManagerServiceMockRecorder
	isgomock struct{}
}

// MockorderManagerServiceMockRecorder is the mock recorder for MockorderManagerService.
type MockorderManagerServiceMockRecorder struct {
	mock *MockorderManagerService
}

// NewMockorderManagerService creates a new mock instance.
func NewMockorderManagerService(ctrl *gomock.Controller) *MockorderManagerService {
	mock := &MockorderManagerService{ctrl: ctrl}
	mock.recorder = &MockorderManagerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderManagerService) EXPECT() *MockorderManagerServiceMockRecorder {
	return m.recorder
}

// OrderChan mocks base method.
func (m *MockorderManagerService) OrderChan() <-chan *dto.OrderDto {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderChan")
	ret0, _ := ret[0].(<-chan *dto.OrderDto)
	return ret0
}

// OrderChan indicates an expected call of OrderChan.
func (mr *MockorderManagerServiceMockRecorder) OrderChan() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderChan", reflect.TypeOf((*MockorderManagerService)(nil).OrderChan))
}

// UpdateOrder mocks base method.
func (m *MockorderManagerService) UpdateOrder(ctx context.Context, arg1 *models.Order) (models.OrderStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, arg1)
	ret0, _ := ret[0].(models.OrderStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockorderManagerServiceMockRecorder) UpdateOrder(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockorderManagerService)(nil).UpdateOrder), ctx, arg1)
}

// MockpauseController is a mock of pauseController interface.
type MockpauseController struct {
	ctrl     *gomock.Controller
	recorder *MockpauseControllerMockRecorder
	isgomock struct{}
}

// MockpauseControllerMockRecorder is the mock recorder for MockpauseController.
type MockpauseControllerMockRecorder struct {
	mock *MockpauseController
}

// NewMockpauseController creates a new mock instance.
func NewMockpauseController(ctrl *gomock.Controller) *MockpauseController {
	mock := &MockpauseController{ctrl: ctrl}
	mock.recorder = &MockpauseControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpauseController) EXPECT() *MockpauseControllerMockRecorder {
	return m.recorder
}

// Pause mocks base method.
func (m *MockpauseController) Pause(dur time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Pause", dur)
}

// Pause indicates an expected call of Pause.
func (mr *MockpauseControllerMockRecorder) Pause(dur any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockpauseController)(nil).Pause), dur)
}

// Wait mocks base method.
func (m *MockpauseController) Wait(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockpauseControllerMockRecorder) Wait(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockpauseController)(nil).Wait), ctx)
}

// MockexternalResultClient is a mock of externalResultClient interface.
type MockexternalResultClient struct {
	ctrl     *gomock.Controller
	recorder *MockexternalResultClientMockRecorder
	isgomock struct{}
}

// MockexternalResultClientMockRecorder is the mock recorder for MockexternalResultClient.
type MockexternalResultClientMockRecorder struct {
	mock *MockexternalResultClient
}

// NewMockexternalResultClient creates a new mock instance.
func NewMockexternalResultClient(ctrl *gomock.Controller) *MockexternalResultClient {
	mock := &MockexternalResultClient{ctrl: ctrl}
	mock.recorder = &MockexternalResultClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexternalResultClient) EXPECT() *MockexternalResultClientMockRecorder {
	return m.recorder
}

// getResultFromExternalSystem mocks base method.
func (m *MockexternalResultClient) getResultFromExternalSystem(ctx context.Context, order dto.OrderDto, appLogger *zap.Logger) (*accrualStatusOrder.OrderDto, *time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getResultFromExternalSystem", ctx, order, appLogger)
	ret0, _ := ret[0].(*accrualStatusOrder.OrderDto)
	ret1, _ := ret[1].(*time.Duration)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// getResultFromExternalSystem indicates an expected call of getResultFromExternalSystem.
func (mr *MockexternalResultClientMockRecorder) getResultFromExternalSystem(ctx, order, appLogger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getResultFromExternalSystem", reflect.TypeOf((*MockexternalResultClient)(nil).getResultFromExternalSystem), ctx, order, appLogger)
}
